function GetSongColor(songtit)
	--Yellow-#FCFA11
	--Lime-#08F80F
	--Blue-#0CAEFF

	--Arcade Colors
	local ACSong = {
		--Yellow
		["Abyss"] = "#FCFA11",
		["SANA MOLLETE NE ENTE"] = "#FCFA11",
		["I Was The One"] = "#FCFA11",
		["Mr.T. (take me higher)"] = "#FCFA11",
		["ABSOLUTE"] = "#FCFA11",
		["THE CUBE"] = "#FCFA11",
		["DXY!"] = "#FCFA11",
		["Radical Faith"] = "#FCFA11",
		["Electro Tuned ( the SubS Mix )"] = "#FCFA11",
		--Green
		["Remember You"] = "#08F80F",
		["ODORU PONPOKOLIN"] = "#08F80F",
		["17SAI"] = "#08F80F",
		["17才"] = "#08F80F",
		["DANCING ALL ALONE"] = "#08F80F",
		["OOPS!...I DID IT AGAIN (Fired Up MIX)"] = "#08F80F",
		["SWING IT"] = "#08F80F",
		["TEST MY BEST"] = "#08F80F",
		["RIGHT NOW"] = "#08F80F",
		["AGAINST ALL ODDS (Definitive MIX)"] = "#08F80F",
		["BE TOGETHER"] = "#08F80F",
		["THE TWIST (Double Pump MIX)"] = "#08F80F",
		["MOVIN ON (Extended Moon Mix)"] = "#08F80F",
		["ROMANCE NO KAMISAMA"] = "#08F80F",
		["NEVER ENDING STORY (Power Club Vocal Mix)"] = "#08F80F",
		["Healing Vision"] = "#08F80F",
		["HOT LIMIT"] = "#08F80F",
		["MOONLIGHT SHADOW (New Vocal Version)"] = "#08F80F",
		["MY GENERATION (Fat Beat Mix)"] = "#08F80F",
		["DIVE"] = "#08F80F",
		["DYNAMITE RAVE(Long ver.)"] = "#08F80F",
		["BROKEN MY HEART"] = "#08F80F",
		["MATSURI JAPAN"] = "#08F80F",
		["ECSTASY"] = "#08F80F",
		["STILL IN MY HEART"] = "#08F80F",
		["TRIBAL DANCE (ALMIGHTY MIX)"] = "#08F80F",
		["AFRONOVA PRIMEVAL"] = "#08F80F",
		["B4U glorious style"] = "#08F80F",
		["CAN'T STOP FALLIN' IN LOVE ~SPEED MIX~"] = "#08F80F",
		["INSERTiON"] = "#08F80F",
		["NO LIMIT(RM Remix)"] = "#08F80F",
		["NO LIMIT (RM Remix)"] = "#08F80F",
		["PARANOiA ETERNAL"] = "#08F80F",
		--Blue
		["1,2,3,4, 007"] = "#0CAEFF",
		["BABY BABY GIMME YOUR LOVE"] = "#0CAEFF",
		["XANADU"] = "#0CAEFF",
		["THE 7 JUMP"] = "#0CAEFF",
		["ONLY YOU"] = "#0CAEFF",
		["EAT YOU UP"] = "#0CAEFF",
		["Let's talk it over"] = "#0CAEFF",
		["GOTCHA (The Theme From STARSKY & HUTCH)"] = "#0CAEFF",
		["Butterfly"] = "#0CAEFF",
		["BUTTERFLY"] = "#0CAEFF",
		["GIMME GIMME GIMME"] = "#0CAEFF",
		["HERO (KCP DISCOTIQUE MIX)"] = "#0CAEFF",
		["SHAKE YOUR BOOTY"] = "#0CAEFF",
		["HIGHER"] = "#0CAEFF",
		["IT ONLY TAKES A MINUTE (Extended Remix)"] = "#0CAEFF",
		["BUMBLE BEE"] = "#0CAEFF",
		["CAFE"] = "#0CAEFF",
		["HAVE YOU NEVER BEEN MELLOW (MM GROOVIN MIX)"] = "#0CAEFF",
		["IN THE HEAT OF THE NIGHT"] = "#0CAEFF",
		["NEVER GONNA MAKE (FACTORY DANCE TEAM MIX)"] = "#0CAEFF",
		["never let you down"] = "#0CAEFF",
		["WALKIE TALKIE"] = "#0CAEFF",
		["Young Forever"] = "#0CAEFF",
		["CAN'T STOP FALLIN' IN LOVE"] = "#0CAEFF",
		["CAT'S EYE (Ventura Mix)"] = "#0CAEFF",
		["CONGA FEELING"] = "#0CAEFF",
		["NA-NA"] = "#0CAEFF",
		["ORION.78(AMeuro-MIX)"] = "#0CAEFF",
		["KICK THE CAN"] = "#0CAEFF",
		["Let the beat hit em!"] = "#0CAEFF",
		["NIGHT IN MOTION"] = "#0CAEFF",
		["PETIT LOVE"] = "#0CAEFF",
		["era (nostalmix)"] = "#0CAEFF",
		["Get me in your sight (AMD CANCUN MIX)"] = "#0CAEFF",
		["DO ME (H.I.G.E.O. MIX)"] = "#0CAEFF",
		["Lupin the 3rd '78"] = "#0CAEFF",
		["MY SUMMER LOVE"] = "#0CAEFF",
		["WILD RUSH"] = "#0CAEFF",
		["BRILLIANT 2U"] = "#0CAEFF",
		["Don't Stop!~AMD 2nd MIX~"] = "#0CAEFF",
		["PINK DINOSAUR"] = "#0CAEFF",
		["SHOOTING STAR"] = "#0CAEFF",
		["B4U"] = "#0CAEFF",
		["SYNCHRONIZED LOVE (Red Monster Hyper Mix)"] = "#0CAEFF",
		[".59"] = "#0CAEFF",
		["BURNIN' THE FLOOR"] = "#0CAEFF",
		["CELEBRATE NITE"] = "#0CAEFF",
		["DAM DARIRAM (KCP MIX)"] = "#0CAEFF",
		["DREAM A DREAM"] = "#0CAEFF",
		["HERO (HAPPY GRANDALE MIX)"] = "#0CAEFF",
		["La Senorita"] = "#0CAEFF",
		["La Señorita"] = "#0CAEFF",
		["LOVE AGAIN TONIGHT~For Melissa MIX~"] = "#0CAEFF",
		["Make Your Move"] = "#0CAEFF",
		["MUSIC"] = "#0CAEFF",
		["ONE TWO (LITTLE BITCH)"] = "#0CAEFF",
		["BOYS (EURO MIX)"] = "#0CAEFF",
		["DAM DARIRAM"] = "#0CAEFF",
		["DUB-I-DUB"] = "#0CAEFF",
		["Holic"] = "#0CAEFF",
		["HYSTERIA"] = "#0CAEFF",
		["IF YOU WERE HERE (B4 ZA BEAT MIX)"] = "#0CAEFF",
		["SKY HIGH"] = "#0CAEFF",
		["THEME FROM ENTER THE DRAGON (notorious mix)"] = "#0CAEFF",
		["RHYTHM AND POLICE (K.O.G G3 Mix)"] = "#0CAEFF",
		["WONDA (SPEED K MIX)"] = "#0CAEFF",
		["END OF THE CENTURY"] = "#0CAEFF",
		["LUV TO ME (AMD MIX)"] = "#0CAEFF",
		["CAPTAIN JACK (GRANDALE REMIX)"] = "#0CAEFF",
		["FURUHATA'S THEME"] = "#0CAEFF",
		["IF YOU WERE HERE"] = "#0CAEFF",
		["SEXY PLANET"] = "#0CAEFF",
		["I Believe In Miracles (The Lisa Marie Experience Radio Edit)"] = "#0CAEFF",
		["stomp to my beat"] = "#0CAEFF",
		["SUPER STAR"] = "#0CAEFF",
		["HYPNOTIC CRISIS"] = "#0CAEFF",
		["BOOM BOOM DOLLAR (K.O.G G3 MIX)"] = "#0CAEFF",
		["BOOM BOOM DOLLAR (K.O.G. G3 MIX)"] = "#0CAEFF",
		["DROP OUT"] = "#0CAEFF",
		["DEAD END"] = "#0CAEFF",
		["DYNAMITE RAVE"] = "#0CAEFF",
		["LEADING CYBER"] = "#0CAEFF",
		["TRIP MACHINE CLIMAX"] = "#0CAEFF",
		["PARANOIA EVOLUTION"] = "#0CAEFF",
		["PARANOiA MAX~DIRTY MIX~"] = "#0CAEFF",
		["PARANOiA MAX～DIRTY MIX～"] = "#0CAEFF",
	}

	--Console Japan Colors
	local CSJPSong = {
		--Yellow
		["DANCING ALL ALONE"] = "#FCFA11",
	}

	--Fallback
	local SongColor = "#000000";

	-- if GAMESTATE:GetCoinMode() == "CoinMode_Home" then
	-- 	SongColor = CSJPSong[songtit] or "#FFFFFF"
	-- else
		SongColor = ACSong[songtit] or "#FFFFFF"
	-- end

	return SongColor;
end;