local t = Def.ActorFrame{
	LoadActor("_howtoplay")..{
		Name="HowToPlayBig";
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-84;zoomy,0);
		OnCommand=cmd(linear,0.384;zoomy,1;sleep,1.216;linear,0.384;zoomy,0);
	};
	LoadActor("_playwithfeet")..{
		Name="PlayWithFeet";
		InitCommand=cmd(CenterX;y,SCREEN_CENTER_Y-88;addx,-SCREEN_WIDTH;zoomx,0.5);
		OnCommand=cmd(sleep,3.417;linear,0.3;addx,SCREEN_WIDTH;zoomx,1;sleep,2.333;linear,0.267;zoomy,0);
	};
	LoadActor(THEME:GetPathG("ScreenGameplay","LifeFrame"))..{
		InitCommand=cmd(CenterX;y,SCREEN_TOP;valign,0;addy,-64;diffuse,color("0,0,0,1"));
		OnCommand=cmd(sleep,9.15;linear,0.35;addy,64;diffuse,color("1,1,1,1"));
	};
	Def.ActorFrame{
		Name="Message1";
		InitCommand=cmd(x,SCREEN_CENTER_X+158;y,SCREEN_CENTER_Y+60;);
		OnCommand=cmd(hibernate,12.150;sleep,1.333;diffusealpha,0);
		Def.Quad{
			InitCommand=cmd(zoomto,308,94;diffuse,color("0,0,0,0.5"));
		};
		LoadActor("single")..{
			InitCommand=cmd(y,12);
		};
	};
	Def.ActorFrame{
		Name="Message2";
		InitCommand=cmd(x,SCREEN_CENTER_X+158;y,SCREEN_CENTER_Y+74;);
		OnCommand=cmd(hibernate,16.484;sleep,1.333;diffusealpha,0);
		Def.Quad{
			InitCommand=cmd(zoomto,308,94;diffuse,color("0,0,0,0.5"));
		};
		LoadActor("single")..{
			InitCommand=cmd(y,12);
		};
	};
	Def.ActorFrame{
		Name="Message3";
		InitCommand=cmd(x,SCREEN_CENTER_X+158;y,SCREEN_CENTER_Y+74;);
		OnCommand=cmd(hibernate,20.817;sleep,1.333;diffusealpha,0);
		Def.Quad{
			InitCommand=cmd(zoomto,308,94;diffuse,color("0,0,0,0.5"));
		};
		LoadActor("single")..{
			InitCommand=cmd(y,12);
		};
	};
	Def.ActorFrame{
		Name="Message4";
		InitCommand=cmd(x,SCREEN_CENTER_X+168;y,SCREEN_CENTER_Y+80;);
		OnCommand=cmd(hibernate,25.150;sleep,1.333;diffusealpha,0);
		Def.Quad{
			InitCommand=cmd(zoomto,262,98;diffuse,color("0,0,0,0.5"));
		};
		LoadActor("jump")..{
			InitCommand=cmd(x,-8;y,-16);
		};
	};
	Def.ActorFrame{
		Name="Message5";
		InitCommand=cmd(x,SCREEN_CENTER_X+158;y,SCREEN_CENTER_Y+74;);
		OnCommand=cmd(hibernate,29.484;sleep,1.333;diffusealpha,0);
		Def.Quad{
			InitCommand=cmd(zoomto,320,144;diffuse,color("0,0,0,0.5"));
		};
		LoadActor("lose")..{
			InitCommand=cmd(y,-8);
		};
	};
};
return t;